# Generated by Django 6.0.5 on 2026-05-06 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_weakarea'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseprogress',
            options={'ordering': ['-last_accessed_at']},
        ),
        migrations.AlterModelOptions(
            name='lessonprogress',
            options={'ordering': ['lesson']},
        ),
        migrations.AlterModelOptions(
            name='weakarea',
            options={'ordering': ['-created_at']},
        ),
    ]
