# Generated by Django 6.0.5 on 2026-05-06 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_quizattempt_quizquestion_quizchoice_quizanswer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizanswer',
            options={'ordering': ['question__order']},
        ),
        migrations.AlterModelOptions(
            name='quizchoice',
            options={'ordering': ['id']},
        ),
    ]
