# Generated by Django 6.0.5 on 2026-05-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='flag_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='summary_message_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
